# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash_submission',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
